# Generated by Django 3.0.3 on 2020-04-24 09:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbres',
            fields=[
                ('gid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'arbres',
            },
        ),
    ]
