# Generated by Django 3.0.3 on 2020-04-24 11:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('gid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'batiments',
            },
        ),
        migrations.CreateModel(
            name='Emplacements',
            fields=[
                ('gid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'emplacements',
            },
        ),
        migrations.CreateModel(
            name='Piscine',
            fields=[
                ('gid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'piscine',
            },
        ),
        migrations.CreateModel(
            name='ZoneCamping',
            fields=[
                ('gid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'zone-camping',
            },
        ),
    ]
